### PR TITLE
added products to products.html

### PR DESCRIPTION
**Pull request by snehaIlager**
added around 11 to 12 products to html page for e - commerce site

### CODE REVIEW

**Comment by amitdsa2024** [comment]
Please arrange all the images of equal size as last two images add to cart button is going up instead of labelling first two. 

 
change

**Comment by snehaIlager** [comment]
Ok sure.. can i know is these products are enough or i could add more??

**Comment by amitdsa2024** [comment]
You mentioned 11 and 12 but here only three are shown. Even structure in one row only. Can u add more rows with four columns each.

**Comment by snehaIlager** [comment]
can u check it now again

**Pull request merged**
